name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'  # كل ساعة
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate stats
        uses: anuraghazra/github-readme-stats@v1
        with:
          username: MohamedAhmed479
          show_icons: true
          theme: default
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update GitHub stats" || echo "No changes to commit"
          git push
